### ISSUE TITLE
Where do we submit the link for our PR? 

### ISSUE THREAD

**Issue by akankshanehete** [Shopify/eng-intern-assessment-data#3]
Hi, 
Where exactly do we submit the link for the PR once we are done the assessment? 

Thank you, 
Akanksha

**Comment by Chief-Zach** [comment]
There is a submission box at the bottom of the smartr.me forum labeled "GitHub Challenge Link".

**Comment by akankshanehete** [comment]
What if I applied on the Shopify site and not smartR?

**Comment by akankshanehete** [comment]
Got it, thank you!
